# Generated by Django 3.1.7 on 2021-02-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ios', '0002_os_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='status',
            field=models.CharField(choices=[('1', 'Iniciado'), ('2', 'Finalizado')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='os',
            name='valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
