# Generated by Django 3.1.7 on 2021-02-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ios', '0003_auto_20210228_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='status',
            field=models.CharField(choices=[('1', 'Não Iniciado'), ('2', 'Iniciado'), ('3', 'Finalizado'), ('4', 'Reaberto')], max_length=2),
        ),
    ]
